package model;

import jakarta.persistence.*;
import lombok.Data;

/**
 * Hibernate entity for the hotels table.
 *
 * @Entity      = This is a Hibernate entity
 * @Table       = which database table is behind it
 * @Id          = Primary key
 * @Column      = Column name if different from field name
 *
 * The ID is NOT generated by the database (no @GeneratedValue),
 * but is assigned manually (max+1). This way we avoid IDENTITY gaps.
 */
@Entity
@Table(name = "hotels")
@Data
public class Hotel {

    @Id
    @Column(name = "id")
    private int id;

    @Column(name = "category")
    private String category;

    @Column(name = "name")
    private String name;

    @Column(name = "owner")
    private String owner;

    @Column(name = "contact")
    private String contact;

    @Column(name = "address")
    private String address;

    @Column(name = "city")
    private String city;

    @Column(name = "cityCode")
    private String cityCode;

    @Column(name = "phone")
    private String phone;

    @Column(name = "noRooms")
    private int noRooms;

    @Column(name = "noBeds")
    private int noBeds;

    @Column(name = "tags")
    private String tags;

    @Override
    public String toString() {
        return id + " - " + name;
    }
}
